version: '3.7'

services:
  postgres:
    image: postgres
    container_name: matricubase
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker_matriculazy
      - POSTGRES_DB=matriculazy
    volumes:
      - pgdata:/data/postgres
  # app:
  #   build: ./server
  #   container_name: matriculazy
  #   ports:
  #     - 3333:3333
  #     - 5555:5555
  #   expose:
  #     - 3333:3333
  #     - 5555:5555
  #   volumes:
  #     - ./server:/usr/app
  #   depends_on:
  #     - postgres
volumes:
  pgdata:
    driver: local
