version: '2.6'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=matriculazy_database
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    depends_on:
      - database
    container_name: matriculazy
    ports:
     - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local